=== 12345ieee/liquibase/src/java/liquibase/dbchangelog-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.liquibase.org/xml/ns/dbchangelog/1.0"
            xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.0"
            elementFormDefault="qualified">

    <!-- This is the main (root) part of the xsd -->
    <xsd:element name="databaseChangeLog">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="preConditions" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:group ref="PreConditionChildren" maxOccurs="unbounded"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>

                <!-- changeSet -->
                <xsd:element name="changeSet" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:group ref="changeSetChildren" maxOccurs="unbounded"/>
                        </xsd:choice>
                        <xsd:attributeGroup ref="changeSetAttributes"/>
                    </xsd:complexType>
                </xsd:element>

                <!-- include -->
                <xsd:element name="include" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="file" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Attributes for DatabaseInfo -->
    <xsd:attributeGroup name="DatabaseInfoAttributes">
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="version" type="xsd:string"/>
        <xsd:attribute name="username" type="xsd:string"/>
        <xsd:attribute name="password" type="xsd:string"/>
        <xsd:attribute name="port" type="xsd:integer"/>
        <xsd:attribute name="host" type="xsd:string"/>
        <xsd:attribute name="schemaName" type="xsd:string"/>
        <xsd:attribute name="driverName" type="xsd:string"/>
    </xsd:attributeGroup>

    <!-- Attributes for changeSet -->
    <xsd:attributeGroup name="changeSetAttributes">
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="author" type="xsd:string"/>
        <xsd:attribute name="context" type="xsd:string"/>
        <xsd:attribute name="runOnChange" type="xsd:boolean"/>
        <xsd:attribute name="runAlways" type="xsd:boolean"/>
    </xsd:attributeGroup>

    <!-- Attributes for constraints -->
    <xsd:attributeGroup name="constraintsAttributes">
        <xsd:attribute name="nullable" type="xsd:boolean"/>
        <xsd:attribute name="primaryKey" type="xsd:boolean"/>
        <xsd:attribute name="unique" type="xsd:boolean"/>
        <xsd:attribute name="references" type="xsd:string"/>
        <xsd:attribute name="foreignKeyName" type="xsd:string"/>
        <xsd:attribute name="deleteCascade" type="xsd:boolean"/>
        <xsd:attribute name="deferrable" type="xsd:boolean"/>
        <xsd:attribute name="initiallyDeferred" type="xsd:boolean"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="column">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="defaultValue" type="xsd:string"/>
        <xsd:attribute name="autoIncrement" type="xsd:boolean"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="dropTableAttributes">
        <xsd:attribute name="tableName" type="xsd:string"/>
        <xsd:attribute name="cascadeConstraints" type="xsd:boolean"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="renameTableAttributes">
        <xsd:attribute name="oldTableName" type="xsd:string"/>
        <xsd:attribute name="newTableName" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="tableNameAttribute">
        <xsd:attribute name="tableName" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="renameColumnAttributes">
        <xsd:attributeGroup ref="tableNameAttribute"/>
        <xsd:attribute name="oldColumnName" type="xsd:string"/>
        <xsd:attribute name="newColumnName" type="xsd:string"/>
        <xsd:attribute name="columnDataType" type="xsd:string"/>        
    </xsd:attributeGroup>

    <xsd:attributeGroup name="dropColumnAttributes">
        <xsd:attributeGroup ref="tableNameAttribute"/>
        <xsd:attribute name="columnName" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="sequenceAttributes">
        <xsd:attribute name="sequenceName" type="xsd:string"/>
        <xsd:attribute name="startValue" type="xsd:string"/>
        <xsd:attribute name="incrementBy" type="xsd:string"/>
        <xsd:attribute name="maxValue" type="xsd:string"/>
        <xsd:attribute name="minValue" type="xsd:string"/>
        <xsd:attribute name="ordered" type="xsd:boolean"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="indexName">
        <xsd:attribute name="indexName" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="createIndex">
        <xsd:attributeGroup ref="tableNameAttribute"/>
        <xsd:attributeGroup ref="indexName"/>
    </xsd:attributeGroup>


    <xsd:attributeGroup name="addNotNullConstraintAttrib">
        <xsd:attribute name="tableName" type="xsd:string"/>
        <xsd:attribute name="columnName" type="xsd:string"/>
        <xsd:attribute name="defaultNullValue" type="xsd:string"/>
        <xsd:attribute name="columnDataType" type="xsd:string"/>
    </xsd:attributeGroup>


    <xsd:element name="addNotNullConstraint">
        <xsd:complexType>
            <xsd:attributeGroup ref="addNotNullConstraintAttrib"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:attributeGroup name="dbmsAttrib">
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:element name="dbms">
        <xsd:complexType>
            <xsd:attributeGroup ref="dbmsAttrib"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="or">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="dbms" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="not">
        <xsd:complexType>

            <xsd:choice>
                <xsd:group ref="NotPreConditionChildren" maxOccurs="unbounded"/>
            </xsd:choice>

        </xsd:complexType>
    </xsd:element>

    <xsd:attributeGroup name="runningAsAttrib">
        <xsd:attribute name="username" type="xsd:string"/>
    </xsd:attributeGroup>

    <xsd:element name="runningAs">
        <xsd:complexType>
            <xsd:attributeGroup ref="runningAsAttrib"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="preConditions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="dbms" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <xsd:attributeGroup name="dropNotNullConstraintAttrib">
        <xsd:attribute name="tableName" type="xsd:string"/>
        <xsd:attribute name="columnName" type="xsd:string"/>
        <xsd:attribute name="columnDataType" type="xsd:string"/>
    </xsd:attributeGroup>


    <xsd:element name="dropNotNullConstraint">
        <xsd:complexType>
            <xsd:attributeGroup ref="dropNotNullConstraintAttrib"/>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="constraints">
        <xsd:complexType>
            <xsd:attributeGroup ref="constraintsAttributes"/>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="column">
        <xsd:complexType mixed="true">
            <xsd:sequence>
                <xsd:element ref="constraints" minOccurs="0"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="column"/>
        </xsd:complexType>
    </xsd:element>

    <!-- Children for createTable -->
    <xsd:element name="createTable">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="tableNameAttribute"/>
        </xsd:complexType>
    </xsd:element>

    <!-- Children for insert -->
    <xsd:element name="insert">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="tableNameAttribute"/>
        </xsd:complexType>
    </xsd:element>

    <!-- Children for addColum -->
    <xsd:element name="addColumn">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="tableNameAttribute"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="rollback" type="xsd:string"/>

    <!-- comment  -->
    <xsd:element name="comment" type="xsd:string"/>

    <!-- sql -->
    <xsd:element name="sql" type="xsd:string"/>

    <!-- renameTable -->
    <xsd:element name="renameTable">
        <xsd:complexType>
            <xsd:attributeGroup ref="renameTableAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <!-- dropTable -->
    <xsd:element name="dropTable">
        <xsd:complexType>
            <xsd:attributeGroup ref="dropTableAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <!-- renameColumn -->
    <xsd:element name="renameColumn">
        <xsd:complexType>
            <xsd:attributeGroup ref="renameColumnAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dropColumn">
        <xsd:complexType>
            <xsd:attributeGroup ref="dropColumnAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="modifyColumn">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="tableNameAttribute"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:group name="whereClause">
        <xsd:sequence>
            <xsd:element name="whereClause" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:element name="createSequence">
        <xsd:complexType>
            <xsd:attributeGroup ref="sequenceAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="alterSequence">
        <xsd:complexType>
            <xsd:attributeGroup ref="sequenceAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dropSequence">
        <xsd:complexType>
            <xsd:attributeGroup ref="sequenceAttributes"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="createIndex">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="createIndex"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dropIndex">
        <xsd:complexType>
            <xsd:attributeGroup ref="tableNameAttribute"/>
            <xsd:attributeGroup ref="indexName"/>
        </xsd:complexType>
    </xsd:element>

    <!-- Children for changeSet -->
    <xsd:group name="changeSetChildren">
        <xsd:choice>
            <xsd:element ref="createTable" maxOccurs="unbounded"/>
            <xsd:element ref="dropTable" maxOccurs="unbounded"/>
            <xsd:element ref="insert" maxOccurs="unbounded"/>
            <xsd:element ref="addColumn" maxOccurs="unbounded"/>
            <xsd:element ref="comment" maxOccurs="unbounded"/>
            <xsd:element ref="sql" maxOccurs="unbounded"/>
            <xsd:element ref="renameTable" maxOccurs="unbounded"/>
            <xsd:element ref="renameColumn" maxOccurs="unbounded"/>
            <xsd:element ref="dropColumn" maxOccurs="unbounded"/>
            <xsd:element ref="modifyColumn" maxOccurs="unbounded"/>
            <xsd:element ref="createSequence" maxOccurs="unbounded"/>
            <xsd:element ref="alterSequence" maxOccurs="unbounded"/>
            <xsd:element ref="dropSequence" maxOccurs="unbounded"/>
            <xsd:element ref="createIndex" maxOccurs="unbounded"/>
            <xsd:element ref="dropIndex" maxOccurs="unbounded"/>
            <xsd:element ref="addNotNullConstraint" maxOccurs="unbounded"/>
            <xsd:element ref="dropNotNullConstraint" maxOccurs="unbounded"/>
            <xsd:element ref="rollback" maxOccurs="1"/>

        </xsd:choice>
    </xsd:group>

    <!-- Children for Precondition -->
    <xsd:group name="PreConditionChildren">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element ref="dbms" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="or" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="not" minOccurs="0" maxOccurs="1"/>
            </xsd:choice>
            <xsd:element ref="runningAs" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>

    </xsd:group>


    <!-- Children for Not Precondition -->
    <xsd:group name="NotPreConditionChildren">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element ref="dbms" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="or" minOccurs="0" maxOccurs="1"/>

            </xsd:choice>

        </xsd:sequence>

    </xsd:group>


</xsd:schema>

=== 12345ieee/liquibase/samples/basic/sample/news/db.changelog.xml
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.0 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.0.xsd">

    <changeSet id="1" author="Alice">
        <createTable tableName="NewsItems">
            <column name="id" type="int">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="title" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="newsDate" type="TIMESTAMP">
                <constraints nullable="false"/>
            </column>
            <column name="author" type="int">
                <constraints nullable="false" foreignKeyName="fk_newsitem_person" references="People(id)"/>
            </column>
            <column name="content" type="CLOB">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>

    <!--changeSet id="2" author="Bob">
        <insert tableName="NewsItems">
            <column name="id" value="1"/>
            <column name="title" value="First Post!"/>
            <column name="newsDate" value="15-SEP-2006 12:15:08"/>
            <column name="author" value="2"/>
            <column name="content" value="Welcome to the news area"/>
        </insert>
        <insert tableName="NewsItems">
            <column name="id" value="2"/>
            <column name="title" value="Second Post!"/>
            <column name="newsDate" value="17-SEP-2006 11:15:08"/>
            <column name="author" value="3"/>
            <column name="content" value="I can welcome you too"/>
        </insert>
    </changeSet-->
    <!--changeSet id="3" author="Bob" runAlways="true">
        <sql>update NewsItems set content=to_char(sysdate) where id=2</sql>
    </changeSet-->
    <!--changeSet id="4" author="Bob" runOnChange="true">
        <sql>update NewsItems set title='Second Post 4', content=to_char(sysdate) where id=1</sql>
    </changeSet-->

</databaseChangeLog>

=== 12345ieee/liquibase/src/samples/changelogs/oracle/rollback/rollbackable.changelog.xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.0 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.0.xsd">
    <preConditions>
            <dbms type="oracle"/>
    </preConditions>

    <changeSet id="1" author="nvoxland">
        <createTable tableName="magazine">
            <column name="id" type="int">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="title" type="varchar(50)">
                <constraints nullable="false"/>
            </column>

        </createTable>
    </changeSet>
    <changeSet id="2" author="nvoxland">
        <addColumn tableName="magazine">
            <column name="sku" type="varchar(50)">
                <constraints nullable="false"/>
            </column>
        </addColumn>
        <createIndex indexName="idx_magazine_sku" tableName="magazine">
            <column name="sku"/>
        </createIndex>
    </changeSet>
    <changeSet id="3" author="nvoxland">
        <dropNotNullConstraint tableName="magazine" columnName="title" columnDataType="varchar(50)"/>
    </changeSet>
    <changeSet id="4" author="nvoxland">
        <renameColumn tableName="magazine" oldColumnName="sku" newColumnName="isbn"/>
    </changeSet>
    <changeSet id="5" author="nvoxland">
        <renameTable oldTableName="magazine" newTableName="publication"/>
    </changeSet>

    <changeSet id="6" author="nvoxland">
        <comment>
            Refactorings that can't be automatically rolled back can be custom rolled back with a "rollback" tag.
        </comment>
        <insert tableName="publication">
            <column name="id" value="1"/>
            <column name="title" value="Refactoring Times"/>
            <column name="isbn" value="12981-512712-512"/>
        </insert>
        <insert tableName="publication">
            <column name="id" value="2"/>
            <column name="title" value="Databases Today"/>
            <column name="isbn" value="51235-632-6232623"/>
        </insert>
        <insert tableName="publication">
            <column name="id" value="3"/>
            <column name="title" value="Newsweek"/>
            <column name="isbn" value="623-6623-332262"/>
        </insert>
        <rollback>
            delete from publication;
        </rollback>
    </changeSet>

    <changeSet id="7" author="nvoxland">
        <addColumn tableName="publication">
            <column name="pages" type="int"/>
        </addColumn>
    </changeSet>
    <changeSet id="8" author="nvoxland">
        <addNotNullConstraint tableName="publication" columnName="title" columnDataType="varchar(50)" defaultNullValue="-1"/>
    </changeSet>

    <changeSet id="9" author="nvoxland">
        <createSequence sequenceName="seq_publication_id"/>
    </changeSet>
</databaseChangeLog>

=== 12345ieee/liquibase/samples/basic/sample/directory/db.changelog.xml
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.0 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.0.xsd">

    <changeSet id="1" author="Alice">
        <createTable tableName="People">
            <column name="id" type="int" autoIncrement="true">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="firstname" type="varchar(255)"/>
            <column name="lastname" type="varchar(255)"/>
            <column name="username" type="varchar(255)">
                <constraints unique="true" nullable="false"/>
            </column>
        </createTable>
    </changeSet>

    <changeSet id="2" author="Alice">
        <insert tableName="People">
            <!--column name="id" value="1"/-->
            <column name="username" value="root"/>
        </insert>
        <insert tableName="People">
            <!--column name="id" value="2"/-->
            <column name="firstname" value="Fred"/>
            <column name="lastname" value="Johnson"/>
            <column name="username" value="fjohnson"/>
        </insert>
        <insert tableName="People">
            <!--column name="id" value="3"/-->
            <column name="firstname" value="Susan"/>
            <column name="lastname" value="Smith"/>
            <column name="username" value="ssmith"/>
        </insert>
    </changeSet>

    <changeSet id="2" author="Bob">
        <insert tableName="People">
            <!--column name="id" value="4"/-->
            <column name="firstname" value="John"/>
            <column name="lastname" value="Doe"/>
            <column name="username" value="jdoe"/>
        </insert>
        <insert tableName="People">
            <!--column name="id" value="5"/-->
            <column name="firstname" value="Ed"/>
            <column name="lastname" value="Jones"/>
            <column name="username" value="ejones"/>
        </insert>
    </changeSet>
</databaseChangeLog>
